version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "5678:5678"
    environment:
      - PYTHONUNBUFFERED=1
    user: "marcu"
    command: /bin/bash -c "while sleep 1000; do :; done"
